### ISSUE TITLE
Exempt SecureLink from scheme checks

### ISSUE THREAD

**Issue by fmarier** [brave/security-action#414]
Reference: https://github.com/brave/brave-core/pull/20452#discussion_r1373981497
![Screenshot from 2023-10-27 11-51-55](https://github.com/brave/security-action/assets/167821/c3e15933-40c5-4613-9503-5b07f42ee3b1)

# Proposed Solution

- [ ] Remove the rule
- [x] Fork and improve the rule

```[tasklist]
### Tasks
- [ ] https://semgrep.dev/r/typescript.react.security.audit.react-href-var.react-href-var
```

**Comment by bcaller** [comment]
Hopefully closed by #417
